language: python
sudo: true
python:
  - 3.7
services:
  - docker
install:
  - pip install -r requirements.txt

before_script:
  - pip install docker-compose

script:
  - docker-compose run web coverage run manage.py test

after_success:
  - coveralls

