// language: python
// # python versions
// python:
//   - "3.7.8"

// services:
//   - postgresql

// addons:
//   postgresql: "9.6"

// # install requirements
// install:
//   - pip install -r requirements.txt
//   - pip install coveralls

// before_script:
//   - psql -c "ALTER USER postgres PASSWORD 'myPassword';"
//   - psql -c 'create database travis_ci_test;' -U postgres

// # To run tests
// script:
//   - coverage run manage.py test

// # send coverage report to coveralls
// after_success:
//   coveralls


language: python
python:
    - 3.6
services:
    - docker
#    - postgresql
install:
    - pip install -r requirements.txt
script:
    - docker-compose run web python manage.py test
deploy:
    provider: script
    script: bash docker_push.sh
    skip_cleanup: true
    on:
        branch: master