# Generated by Django 3.2.4 on 2021-06-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("bred_for", models.TextField()),
                ("bred_group", models.TextField()),
                ("weight", models.JSONField()),
                ("height", models.JSONField()),
                ("reference_image_id", models.CharField(db_index=True, max_length=255)),
                ("life_span", models.TextField()),
                ("temperament", models.TextField()),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
    ]
