# Generated by Django 3.2.4 on 2021-06-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dog",
            name="image",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="dog",
            name="origin",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="dog",
            name="height",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="dog",
            name="weight",
            field=models.JSONField(default=dict),
        ),
    ]
