# Generated by Django 3.2.4 on 2021-06-03 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0002_auto_20210603_1031"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dog",
            old_name="bred_group",
            new_name="breed_group",
        ),
    ]
