# Generated by Django 3.2.4 on 2021-06-03 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0003_rename_bred_group_dog_breed_group"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dog",
            options={},
        ),
        migrations.RemoveField(
            model_name="dog",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="dog",
            name="updated_at",
        ),
    ]
