# Generated by Django 3.2.4 on 2021-06-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0004_auto_20210603_1048"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dog",
            name="bred_for",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="dog",
            name="breed_group",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="dog",
            name="life_span",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="dog",
            name="name",
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="dog",
            name="reference_image_id",
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="dog",
            name="slug",
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="dog",
            name="temperament",
            field=models.TextField(null=True),
        ),
    ]
