# Generated by Django 3.2.4 on 2021-06-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0005_auto_20210603_1051"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dog",
            name="origin",
            field=models.TextField(null=True),
        ),
    ]
