# Generated by Django 3.2.4 on 2021-06-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0006_alter_dog_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="dog",
            name="initial_id",
            field=models.IntegerField(default=0),
        ),
    ]
