# Generated by Django 3.2.4 on 2021-06-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0007_dog_initial_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dog",
            name="bred_for",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dog",
            name="breed_group",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dog",
            name="life_span",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dog",
            name="name",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dog",
            name="origin",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dog",
            name="reference_image_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dog",
            name="temperament",
            field=models.TextField(blank=True, null=True),
        ),
    ]
