# Generated by Django 3.2.4 on 2021-06-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0008_auto_20210604_0738"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dog",
            name="initial_id",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
